/*
 * ============================================================
 * V21 - Seed demo room inventory for Puri Heritage Stay
 * ============================================================
 *
 * Property:
 *   Puri Heritage Stay
 *
 * Current demo property ID:
 *   2
 *
 * Purpose:
 *   Ensure the demo property has usable daily inventory
 *   for future availability searches and booking tests.
 *
 * The application checks room_inventory_daily for EVERY
 * requested night. Without these rows the availability API
 * correctly returns an empty list.
 * ============================================================
 */

-- ------------------------------------------------------------
-- 1. Ensure the demo property has usable room inventory
-- ------------------------------------------------------------

UPDATE room_types
SET
    total_inventory = CASE
                          WHEN total_inventory IS NULL OR total_inventory <= 0
                              THEN 5
                          ELSE total_inventory
        END,
    is_active = TRUE
WHERE property_id = 2;


/*
 * ------------------------------------------------------------
 * 2. Create daily inventory for the next 365 days
 * ------------------------------------------------------------
 *
 * We generate inventory for every active room type belonging
 * to property 2.
 *
 * Existing inventory rows are preserved.
 *
 * available_inventory is initialized as:
 *
 *     total_inventory - reserved_inventory
 *
 * reserved_inventory starts at 0.
 * ------------------------------------------------------------
 */

INSERT INTO room_inventory_daily (
    room_type_id,
    inventory_date,
    total_inventory,
    reserved_inventory,
    available_inventory
)
SELECT
    rt.room_type_id,
    DATE_ADD(CURRENT_DATE, INTERVAL numbers.day_offset DAY),
    rt.total_inventory,
    0,
    rt.total_inventory
FROM room_types rt
         JOIN (
    SELECT 0 AS day_offset
    UNION ALL SELECT 1
    UNION ALL SELECT 2
    UNION ALL SELECT 3
    UNION ALL SELECT 4
    UNION ALL SELECT 5
    UNION ALL SELECT 6
    UNION ALL SELECT 7
    UNION ALL SELECT 8
    UNION ALL SELECT 9
    UNION ALL SELECT 10
    UNION ALL SELECT 11
    UNION ALL SELECT 12
    UNION ALL SELECT 13
    UNION ALL SELECT 14
    UNION ALL SELECT 15
    UNION ALL SELECT 16
    UNION ALL SELECT 17
    UNION ALL SELECT 18
    UNION ALL SELECT 19
    UNION ALL SELECT 20
    UNION ALL SELECT 21
    UNION ALL SELECT 22
    UNION ALL SELECT 23
    UNION ALL SELECT 24
    UNION ALL SELECT 25
    UNION ALL SELECT 26
    UNION ALL SELECT 27
    UNION ALL SELECT 28
    UNION ALL SELECT 29
    UNION ALL SELECT 30
    UNION ALL SELECT 31
    UNION ALL SELECT 32
    UNION ALL SELECT 33
    UNION ALL SELECT 34
    UNION ALL SELECT 35
    UNION ALL SELECT 36
    UNION ALL SELECT 37
    UNION ALL SELECT 38
    UNION ALL SELECT 39
    UNION ALL SELECT 40
    UNION ALL SELECT 41
    UNION ALL SELECT 42
    UNION ALL SELECT 43
    UNION ALL SELECT 44
    UNION ALL SELECT 45
    UNION ALL SELECT 46
    UNION ALL SELECT 47
    UNION ALL SELECT 48
    UNION ALL SELECT 49
    UNION ALL SELECT 50
    UNION ALL SELECT 51
    UNION ALL SELECT 52
    UNION ALL SELECT 53
    UNION ALL SELECT 54
    UNION ALL SELECT 55
    UNION ALL SELECT 56
    UNION ALL SELECT 57
    UNION ALL SELECT 58
    UNION ALL SELECT 59
    UNION ALL SELECT 60
    UNION ALL SELECT 61
    UNION ALL SELECT 62
    UNION ALL SELECT 63
    UNION ALL SELECT 64
    UNION ALL SELECT 65
    UNION ALL SELECT 66
    UNION ALL SELECT 67
    UNION ALL SELECT 68
    UNION ALL SELECT 69
    UNION ALL SELECT 70
    UNION ALL SELECT 71
    UNION ALL SELECT 72
    UNION ALL SELECT 73
    UNION ALL SELECT 74
    UNION ALL SELECT 75
    UNION ALL SELECT 76
    UNION ALL SELECT 77
    UNION ALL SELECT 78
    UNION ALL SELECT 79
    UNION ALL SELECT 80
    UNION ALL SELECT 81
    UNION ALL SELECT 82
    UNION ALL SELECT 83
    UNION ALL SELECT 84
    UNION ALL SELECT 85
    UNION ALL SELECT 86
    UNION ALL SELECT 87
    UNION ALL SELECT 88
    UNION ALL SELECT 89
    UNION ALL SELECT 90
    UNION ALL SELECT 91
    UNION ALL SELECT 92
    UNION ALL SELECT 93
    UNION ALL SELECT 94
    UNION ALL SELECT 95
    UNION ALL SELECT 96
    UNION ALL SELECT 97
    UNION ALL SELECT 98
    UNION ALL SELECT 99
    UNION ALL SELECT 100
    UNION ALL SELECT 101
    UNION ALL SELECT 102
    UNION ALL SELECT 103
    UNION ALL SELECT 104
    UNION ALL SELECT 105
    UNION ALL SELECT 106
    UNION ALL SELECT 107
    UNION ALL SELECT 108
    UNION ALL SELECT 109
    UNION ALL SELECT 110
    UNION ALL SELECT 111
    UNION ALL SELECT 112
    UNION ALL SELECT 113
    UNION ALL SELECT 114
    UNION ALL SELECT 115
    UNION ALL SELECT 116
    UNION ALL SELECT 117
    UNION ALL SELECT 118
    UNION ALL SELECT 119
    UNION ALL SELECT 120
    UNION ALL SELECT 121
    UNION ALL SELECT 122
    UNION ALL SELECT 123
    UNION ALL SELECT 124
    UNION ALL SELECT 125
    UNION ALL SELECT 126
    UNION ALL SELECT 127
    UNION ALL SELECT 128
    UNION ALL SELECT 129
    UNION ALL SELECT 130
    UNION ALL SELECT 131
    UNION ALL SELECT 132
    UNION ALL SELECT 133
    UNION ALL SELECT 134
    UNION ALL SELECT 135
    UNION ALL SELECT 136
    UNION ALL SELECT 137
    UNION ALL SELECT 138
    UNION ALL SELECT 139
    UNION ALL SELECT 140
    UNION ALL SELECT 141
    UNION ALL SELECT 142
    UNION ALL SELECT 143
    UNION ALL SELECT 144
    UNION ALL SELECT 145
    UNION ALL SELECT 146
    UNION ALL SELECT 147
    UNION ALL SELECT 148
    UNION ALL SELECT 149
    UNION ALL SELECT 150
    UNION ALL SELECT 151
    UNION ALL SELECT 152
    UNION ALL SELECT 153
    UNION ALL SELECT 154
    UNION ALL SELECT 155
    UNION ALL SELECT 156
    UNION ALL SELECT 157
    UNION ALL SELECT 158
    UNION ALL SELECT 159
    UNION ALL SELECT 160
    UNION ALL SELECT 161
    UNION ALL SELECT 162
    UNION ALL SELECT 163
    UNION ALL SELECT 164
    UNION ALL SELECT 165
    UNION ALL SELECT 166
    UNION ALL SELECT 167
    UNION ALL SELECT 168
    UNION ALL SELECT 169
    UNION ALL SELECT 170
    UNION ALL SELECT 171
    UNION ALL SELECT 172
    UNION ALL SELECT 173
    UNION ALL SELECT 174
    UNION ALL SELECT 175
    UNION ALL SELECT 176
    UNION ALL SELECT 177
    UNION ALL SELECT 178
    UNION ALL SELECT 179
    UNION ALL SELECT 180
    UNION ALL SELECT 181
    UNION ALL SELECT 182
    UNION ALL SELECT 183
    UNION ALL SELECT 184
    UNION ALL SELECT 185
    UNION ALL SELECT 186
    UNION ALL SELECT 187
    UNION ALL SELECT 188
    UNION ALL SELECT 189
    UNION ALL SELECT 190
    UNION ALL SELECT 191
    UNION ALL SELECT 192
    UNION ALL SELECT 193
    UNION ALL SELECT 194
    UNION ALL SELECT 195
    UNION ALL SELECT 196
    UNION ALL SELECT 197
    UNION ALL SELECT 198
    UNION ALL SELECT 199
    UNION ALL SELECT 200
    UNION ALL SELECT 201
    UNION ALL SELECT 202
    UNION ALL SELECT 203
    UNION ALL SELECT 204
    UNION ALL SELECT 205
    UNION ALL SELECT 206
    UNION ALL SELECT 207
    UNION ALL SELECT 208
    UNION ALL SELECT 209
    UNION ALL SELECT 210
    UNION ALL SELECT 211
    UNION ALL SELECT 212
    UNION ALL SELECT 213
    UNION ALL SELECT 214
    UNION ALL SELECT 215
    UNION ALL SELECT 216
    UNION ALL SELECT 217
    UNION ALL SELECT 218
    UNION ALL SELECT 219
    UNION ALL SELECT 220
    UNION ALL SELECT 221
    UNION ALL SELECT 222
    UNION ALL SELECT 223
    UNION ALL SELECT 224
    UNION ALL SELECT 225
    UNION ALL SELECT 226
    UNION ALL SELECT 227
    UNION ALL SELECT 228
    UNION ALL SELECT 229
    UNION ALL SELECT 230
    UNION ALL SELECT 231
    UNION ALL SELECT 232
    UNION ALL SELECT 233
    UNION ALL SELECT 234
    UNION ALL SELECT 235
    UNION ALL SELECT 236
    UNION ALL SELECT 237
    UNION ALL SELECT 238
    UNION ALL SELECT 239
    UNION ALL SELECT 240
    UNION ALL SELECT 241
    UNION ALL SELECT 242
    UNION ALL SELECT 243
    UNION ALL SELECT 244
    UNION ALL SELECT 245
    UNION ALL SELECT 246
    UNION ALL SELECT 247
    UNION ALL SELECT 248
    UNION ALL SELECT 249
    UNION ALL SELECT 250
    UNION ALL SELECT 251
    UNION ALL SELECT 252
    UNION ALL SELECT 253
    UNION ALL SELECT 254
    UNION ALL SELECT 255
    UNION ALL SELECT 256
    UNION ALL SELECT 257
    UNION ALL SELECT 258
    UNION ALL SELECT 259
    UNION ALL SELECT 260
    UNION ALL SELECT 261
    UNION ALL SELECT 262
    UNION ALL SELECT 263
    UNION ALL SELECT 264
    UNION ALL SELECT 265
    UNION ALL SELECT 266
    UNION ALL SELECT 267
    UNION ALL SELECT 268
    UNION ALL SELECT 269
    UNION ALL SELECT 270
    UNION ALL SELECT 271
    UNION ALL SELECT 272
    UNION ALL SELECT 273
    UNION ALL SELECT 274
    UNION ALL SELECT 275
    UNION ALL SELECT 276
    UNION ALL SELECT 277
    UNION ALL SELECT 278
    UNION ALL SELECT 279
    UNION ALL SELECT 280
    UNION ALL SELECT 281
    UNION ALL SELECT 282
    UNION ALL SELECT 283
    UNION ALL SELECT 284
    UNION ALL SELECT 285
    UNION ALL SELECT 286
    UNION ALL SELECT 287
    UNION ALL SELECT 288
    UNION ALL SELECT 289
    UNION ALL SELECT 290
    UNION ALL SELECT 291
    UNION ALL SELECT 292
    UNION ALL SELECT 293
    UNION ALL SELECT 294
    UNION ALL SELECT 295
    UNION ALL SELECT 296
    UNION ALL SELECT 297
    UNION ALL SELECT 298
    UNION ALL SELECT 299
    UNION ALL SELECT 300
    UNION ALL SELECT 301
    UNION ALL SELECT 302
    UNION ALL SELECT 303
    UNION ALL SELECT 304
    UNION ALL SELECT 305
    UNION ALL SELECT 306
    UNION ALL SELECT 307
    UNION ALL SELECT 308
    UNION ALL SELECT 309
    UNION ALL SELECT 310
    UNION ALL SELECT 311
    UNION ALL SELECT 312
    UNION ALL SELECT 313
    UNION ALL SELECT 314
    UNION ALL SELECT 315
    UNION ALL SELECT 316
    UNION ALL SELECT 317
    UNION ALL SELECT 318
    UNION ALL SELECT 319
    UNION ALL SELECT 320
    UNION ALL SELECT 321
    UNION ALL SELECT 322
    UNION ALL SELECT 323
    UNION ALL SELECT 324
    UNION ALL SELECT 325
    UNION ALL SELECT 326
    UNION ALL SELECT 327
    UNION ALL SELECT 328
    UNION ALL SELECT 329
    UNION ALL SELECT 330
    UNION ALL SELECT 331
    UNION ALL SELECT 332
    UNION ALL SELECT 333
    UNION ALL SELECT 334
    UNION ALL SELECT 335
    UNION ALL SELECT 336
    UNION ALL SELECT 337
    UNION ALL SELECT 338
    UNION ALL SELECT 339
    UNION ALL SELECT 340
    UNION ALL SELECT 341
    UNION ALL SELECT 342
    UNION ALL SELECT 343
    UNION ALL SELECT 344
    UNION ALL SELECT 345
    UNION ALL SELECT 346
    UNION ALL SELECT 347
    UNION ALL SELECT 348
    UNION ALL SELECT 349
    UNION ALL SELECT 350
    UNION ALL SELECT 351
    UNION ALL SELECT 352
    UNION ALL SELECT 353
    UNION ALL SELECT 354
    UNION ALL SELECT 355
    UNION ALL SELECT 356
    UNION ALL SELECT 357
    UNION ALL SELECT 358
    UNION ALL SELECT 359
    UNION ALL SELECT 360
    UNION ALL SELECT 361
    UNION ALL SELECT 362
    UNION ALL SELECT 363
    UNION ALL SELECT 364
) numbers
WHERE rt.property_id = 2
  AND rt.is_active = TRUE

    /*
     * Prevent duplicate inventory rows if a matching row
     * already exists.
     */
  AND NOT EXISTS (
    SELECT 1
    FROM room_inventory_daily existing
    WHERE existing.room_type_id = rt.room_type_id
      AND existing.inventory_date =
          DATE_ADD(
                          CURRENT_DATE,
                          INTERVAL numbers.day_offset DAY
          )
);