ALTER TABLE users
MODIFY COLUMN role ENUM(
    'ROLE_GUEST',
    'ROLE_USER',
    'ROLE_HOTEL_PARTNER',
    'ROLE_GUIDE_PARTNER',
    'ROLE_CAB_PARTNER',
    'ROLE_SUPER_ADMIN'
) NOT NULL DEFAULT 'ROLE_USER';
